[build]
  command = "npm run build"
  publish = "out"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NEXT_PUBLIC_API_URL = "/.netlify/functions"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  external_node_modules = ["@mongodb-js/zstd", "mongodb-client-encryption", "snappy"]
  included_files = ["dist/napi-v3-linux-x64-glibc/*"] 